const saveDefaultPmgObj = () => {
  // Check if pmgObj exists in localStorage
  if (!localStorage.getItem("pmgObj")) {
    // If not, save the default pmgObj
    localStorage.setItem(
      "pmgObj",
      JSON.stringify({
        pmgSettings: {
          pmgId: 135,
          pmgMaxPower: 600000,
          settleTimeParameter: 1,
          powerBlockAllocationSize: 1000,
          thresholdLowOffsetParameter: 10000,
          thresholdHighOffsetParameter: 5000,
        },
        connectorsDetails: [
          {
            connectorId: 1,
            chargeStationId: 1,
            CSMaxPower: 160000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 0,
            chargingStartedAt: 57,
            chargingStoppedAt: 93,
            isSaved: true,
          },
          {
            connectorId: 2,
            chargeStationId: 1,
            CSMaxPower: 160000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 46,
            chargingStartedAt: 1,
            chargingStoppedAt: 54,
            isSaved: true,
          },
          {
            connectorId: 3,
            chargeStationId: 2,
            CSMaxPower: 120000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 46,
            chargingStartedAt: 4,
            chargingStoppedAt: 95,
            isSaved: true,
          },
          {
            connectorId: 4,
            chargeStationId: 2,
            CSMaxPower: 120000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 46,
            chargingStartedAt: 30,
            chargingStoppedAt: 98,
            isSaved: true,
          },
          {
            connectorId: 5,
            chargeStationId: 3,
            CSMaxPower: 160000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 46,
            chargingStartedAt: 9,
            chargingStoppedAt: 59,
            isSaved: true,
          },
          {
            connectorId: 6,
            chargeStationId: 3,
            CSMaxPower: 160000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 0,
            chargingStartedAt: 64,
            chargingStoppedAt: 103,
            isSaved: true,
          },
          {
            connectorId: 7,
            chargeStationId: 4,
            CSMaxPower: 120000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 0,
            chargingStartedAt: 70,
            chargingStoppedAt: 105,
            isSaved: true,
          },
          {
            connectorId: 8,
            chargeStationId: 4,
            CSMaxPower: 120000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 46,
            chargingStartedAt: 13,
            chargingStoppedAt: 68,
            isSaved: true,
          },
          {
            connectorId: 9,
            chargeStationId: 5,
            CSMaxPower: 180000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 46,
            chargingStartedAt: 16,
            chargingStoppedAt: 72,
            isSaved: true,
          },
          {
            connectorId: 10,
            chargeStationId: 5,
            CSMaxPower: 180000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 46,
            chargingStartedAt: 34,
            chargingStoppedAt: 75,
            isSaved: true,
          },
          {
            connectorId: 11,
            chargeStationId: 6,
            CSMaxPower: 200000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 46,
            chargingStartedAt: 19,
            chargingStoppedAt: 79,
            isSaved: true,
          },
          {
            connectorId: 12,
            chargeStationId: 6,
            CSMaxPower: 200000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 46,
            chargingStartedAt: 40,
            chargingStoppedAt: 83,
            isSaved: true,
          },
          {
            connectorId: 13,
            chargeStationId: 7,
            CSMaxPower: 160000,
            connectorMaxPower: 60000,
            connectorDefaultPower: 46,
            chargingStartedAt: 22,
            chargingStoppedAt: 87,
            isSaved: true,
          },
          {
            connectorId: 14,
            chargeStationId: 7,
            CSMaxPower: 160000,
            connectorMaxPower: 120000,
            connectorDefaultPower: 46,
            chargingStartedAt: 45,
            chargingStoppedAt: 89,
            isSaved: true,
          },
          {
            connectorId: 15,
            chargeStationId: 8,
            CSMaxPower: 120000,
            connectorMaxPower: 130000,
            connectorDefaultPower: 46,
            chargingStartedAt: 26,
            chargingStoppedAt: 107,
            isSaved: true,
          },
          {
            connectorId: 16,
            chargeStationId: 8,
            CSMaxPower: 120000,
            connectorMaxPower: 140000,
            connectorDefaultPower: 46,
            chargingStartedAt: 50,
            chargingStoppedAt: 111,
            isSaved: true,
          },
        ],
      })
    );
  }
};

export default saveDefaultPmgObj;
